// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUyHe0DP_bt2BycQyOM0w44KzmCQIImDY',
    appId: '1:490791992706:web:1a2f17093ffabfae41639b',
    messagingSenderId: '490791992706',
    projectId: 'worker-system-2024',
    authDomain: 'worker-system-2024.firebaseapp.com',
    storageBucket: 'worker-system-2024.firebasestorage.app',
    measurementId: 'G-6SCKTYEF34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-vl5O0lFKtbJ7WTvZXml0ovIEONOiGi0',
    appId: '1:490791992706:android:f2a0773cd63dfaed41639b',
    messagingSenderId: '490791992706',
    projectId: 'worker-system-2024',
    storageBucket: 'worker-system-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzfSoR6qb2jSqluMDaqaawkyUW3gid9Xo',
    appId: '1:490791992706:ios:42f5e85854a1e29541639b',
    messagingSenderId: '490791992706',
    projectId: 'worker-system-2024',
    storageBucket: 'worker-system-2024.firebasestorage.app',
    iosBundleId: 'com.workerappadmin.workerappadmin',
  );
}
